### ISSUE TITLE
你这翻译的什么破玩意

### ISSUE THREAD

**Issue by jiyuan72** [coderLMN/BigDataAnalytics#1]
我拿到书之后一翻 退货 不bb
什么乱七八糟的破玩意来坑人，你翻译全了吗，每个子目录一两行一提，尤其是hbase-kafka那个例子，前面翻译说通过一个例子来说明建表，写数据进去 建完表尼玛完事了 你想偷工减料到什么地步 糊弄鬼呢 你这种sb出什么书，该干嘛该嘛去号码

**Comment by gavinjp** [comment]
![1](https://user-images.githubusercontent.com/22143753/30191691-2488628a-9475-11e7-8674-c05a37455598.png)

**Comment by jiyuan72** [comment]
好吧 算我sb了 我错怪你了。 想不明白这种书存在的意义，新手越看越懵，稍微了解点的看不到一点干货，为了凑满减一并买的，这下好了 擦

**Comment by gavinjp** [comment]
我不是译者……我也是买了书看的……
